export declare const proFormaLeveredReturnsWidget: import("@stratiqai/dashboard-widget-sdk").WidgetManifest<{
    leveredDiscountRate: number;
    projectionYears: number;
    purchasePrice: number;
    acquisitionCosts: number;
    initialCapEx: number;
    egiYear1: number;
    egiGrowthRate: number;
    totalOpexYear1: number;
    opexGrowthRate: number;
    terminalCapRate: number;
    costOfSalePercent: number;
    loanLtv: number;
    loanInterestRate: number;
    amortizationYears: number;
    interestOnly: boolean;
    propertyName?: string | undefined;
}>;
export type { ProFormaLeveredReturnsConfig, ProFormaLeveredReturnsInput, ProFormaLeveredReturnsAiOutput } from './schema.js';
export { proFormaLeveredReturnsConfigSchema, proFormaLeveredReturnsInputSchema, proFormaLeveredReturnsAiOutputSchema } from './schema.js';
