import { z } from 'zod';

export const paragraphWidgetDataSchema = z.object({
	title: z.string().nullable().optional(),
	content: z.string().min(1, 'Content is required'),
	markdown: z.boolean().nullable().default(false)
});

export type ParagraphWidgetData = z.infer<typeof paragraphWidgetDataSchema>;

/**
 * AI output schema: the shape the AI model must return.
 * The `text` field receives the main response text.
 */
export const paragraphAiOutputSchema = z.object({
	text: z.string().describe('The paragraph content generated by the AI')
});

export type ParagraphAiOutput = z.infer<typeof paragraphAiOutputSchema>;
